AcmeHelloBundle:
    resource: "@AcmeHelloBundle/Resources/config/routing.php"
    prefix:   /

AcmeHelloBundle_subscribers:
        resource: "@AcmeHelloBundle/Resources/config/routing/subscribers.php"
        prefix:   /subscribers


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
